name: Deploy Latest code
on:
  pull_request:
    types:
      - closed

jobs:  

  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        persist-credentials: true

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Create local changes and push upstream
      run: |
        yarn install
        yarn run build
        COMMIT_MSG=$(git log --pretty=oneline --abbrev-commit | head -n1 | cut -d ' ' -f 2-)
        cd dist
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git config --global init.defaultBranch "master"
        git init
        git add -A
        git commit -m "${COMMIT_MSG}" -a
        git push -f git@github.com:tommybrecher/tommybrecher.github.io.git master
